services:
  churn-app:
    env_file:
      - ./.env
    build:
      dockerfile: Dockerfile
    ports:
      - "${APP_VM_PORT}:${APP_DOCKER_PORT}"
    volumes:
      - type: bind
        source: ./models
        target: /app/models
